### PR TITLE
Collaborative Project 3: Positioning and Floating Elements

### PR DESCRIPTION
**Pull request by Samitti**
An Example Repo for microverse Projects path as a mockup of the New-York Times page. It contains an exact copy of the layout.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
### Good job Team 👏 👏 
### I think you have really put a lot of creativity into this project. The page looks great but you still need to make few adjustments before this project can be approved.

**_1. Although the pull request comment is okay, you can still improve it._**

**_2. Enable stickler for this project._**

**_3. The navbar should be fixed to the top of the page (i.e. it sticks to the top part of the screen)_** ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

**_4. The footer should also be fixed (i.e. it sticks to the bottom part of the screen)_** ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

**_The original page:_**

image

**_5. Improve the Html semantic of the page. The basic example of an Html page structure:_**
`<header></header> <main></main> <footer></footer>`

**_6. Fix the CSS rule in line 75 of the stylesheet._**

image

**_7. It is required to combine float, flex, and grid as mentioned in the project requirements:_**
Elements aligned with a combination of all three techniques ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction))

**_I think float is missing from your style rules_**

**_Kindly implement these and submit for review._**

**_If you have any doubt or question contact me on slack._**

### Reviewed by: Temitayo Adeleke

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Require changes

**Comment by Samitti** [comment]
# Adjustments made as per the code review request.
-We enabled the stickler for this project.
-We fixed the navbar to the top of the page.
-We fixed the footer element at the bottom of the screen.
-Improved the HTML semantics of the page.( <header></header> <main></main> <footer></footer>).
-We used the float to position the aside element.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Samitti and @JelilFaisalAbudu 
### Good job you have done so far and for implementing changes from the previous reviews :clap: However, you have an issue to work on before your application can be approved.
- Validate your html code and resolve the errors [use this online tool](https://validator.w3.org/#validate_by_upload)
validator

### Make this change and resubmit for another code review. Good luck.
- Happy coding!

**Comment by JelilFaisalAbudu** [comment]
# HTMLCode Validation
-The HTML file validated using the W3 HTML validator and all the errors resolved per the code review request.

**Review by rOluochKe — APPROVED** [review]
Hello @Samitti and @JelilFaisalAbudu 
### Good job done and for making changes from previous reviews. Having verified, your project looks good and I, therefore, approve of it. :boom: :100:
### You can merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
